version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16  # Use the next-gen CircleCI image for Node.js
    steps:
      - checkout
      - run:
          name: Navigate to server directory
          command: cd server && npm install
      - run:
          name: Build project
          command: cd server && npm run build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
